f34: temporarily disable updates
Something is broken in the updates toolchain:

STEP 6/14: RUN dnf --nodocs -y --best --allowerasing install @buildsys-build ccache git make popt-devel nss-devel nspr-devel gettext elfutils-libelf-devel make gcc binutils clang-analyzer 'binutils-*-linux-gnu' 'gcc-*-linux-gnu' 'mingw*-binutils' 'mingw*-gcc' efivar-devel
Fedora 34 - x86_64 - Updates                     54 kB/s |  11 kB     00:00
Fedora 34 - x86_64                               87 kB/s |  11 kB     00:00
Error:
 Problem 1: cannot install both cross-gcc-common-10.2.1-3.fc34.2.noarch and cross-gcc-common-11.2.1-1.fc34.noarch
  - package gcc-cris-linux-gnu-10.2.1-3.fc34.2.x86_64 requires cross-gcc-common = 10.2.1-3.fc34.2, but none of the providers can be installed
  - package gcc-openrisc-linux-gnu-11.2.1-1.fc34.x86_64 requires cross-gcc-common = 11.2.1-1.fc34, but none of the providers can be installed
  - conflicting requests
 Problem 2: cannot install both cross-gcc-common-10.2.1-3.fc34.2.noarch and cross-gcc-common-11.2.1-1.fc34.noarch
  - package gcc-aarch64-linux-gnu-11.2.1-1.fc34.x86_64 requires cross-gcc-common = 11.2.1-1.fc34, but none of the providers can be installed
  - package gcc-sh-linux-gnu-10.2.1-3.fc34.2.x86_64 requires cross-gcc-common = 10.2.1-3.fc34.2, but none of the providers can be installed
  - cannot install the best candidate for the job
  - conflicting requests
 Problem 3: cannot install both cross-gcc-common-10.2.1-3.fc34.2.noarch and cross-gcc-common-11.2.1-1.fc34.noarch
  - package gcc-cris-linux-gnu-10.2.1-3.fc34.2.x86_64 requires cross-gcc-common = 10.2.1-3.fc34.2, but none of the providers can be installed
  - package gcc-alpha-linux-gnu-11.2.1-1.fc34.x86_64 requires cross-gcc-common = 11.2.1-1.fc34, but none of the providers can be installed
  - package gcc-c++-cris-linux-gnu-10.2.1-3.fc34.2.x86_64 requires gcc-cris-linux-gnu = 10.2.1-3.fc34.2, but none of the providers can be installed
  - cannot install the best candidate for the job
  - conflicting requests
 Problem 4: cannot install both cross-gcc-common-10.2.1-3.fc34.2.noarch and cross-gcc-common-11.2.1-1.fc34.noarch
  - package gcc-sh-linux-gnu-10.2.1-3.fc34.2.x86_64 requires cross-gcc-common = 10.2.1-3.fc34.2, but none of the providers can be installed
  - package gcc-arc-linux-gnu-11.2.1-1.fc34.x86_64 requires cross-gcc-common = 11.2.1-1.fc34, but none of the providers can be installed
  - package gcc-c++-sh-linux-gnu-10.2.1-3.fc34.2.x86_64 requires gcc-sh-linux-gnu = 10.2.1-3.fc34.2, but none of the providers can be installed
  - cannot install the best candidate for the job
  - conflicting requests
(try to add '--skip-broken' to skip uninstallable packages)
Error: error building at STEP "RUN dnf --nodocs -y --best --allowerasing install @buildsys-build ccache git make popt-devel nss-devel nspr-devel gettext elfutils-libelf-devel make gcc binutils clang-analyzer 'binutils-*-linux-gnu' 'gcc-*-linux-gnu' 'mingw*-binutils' 'mingw*-gcc' efivar-devel": error while running runtime: exit status 1

So just skip those packages for now.

Signed-off-by: Peter Jones <pjones@redhat.com>